/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -i pdfviewer_adaptor.h -a :pdfviewer_adaptor.cpp pdfviewer.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "pdfviewer_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class PdfViewerAdaptor
 */

PdfViewerAdaptor::PdfViewerAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

PdfViewerAdaptor::~PdfViewerAdaptor()
{
    // destructor
}

QString PdfViewerAdaptor::currentDocument()
{
    // handle method call glad.PdfViewer.currentDocument
    QString out0;
    QMetaObject::invokeMethod(parent(), "currentDocument", Q_RETURN_ARG(QString, out0));
    return out0;
}

void PdfViewerAdaptor::syncFromSource(const QString &sourceFile, int lineNumber)
{
    // handle method call glad.PdfViewer.syncFromSource
    QMetaObject::invokeMethod(parent(), "syncFromSource", Q_ARG(QString, sourceFile), Q_ARG(int, lineNumber));
}

