/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -a pdfviewer_adaptor.h: pdfviewer.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef PDFVIEWER_ADAPTOR_H_1334223675
#define PDFVIEWER_ADAPTOR_H_1334223675

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface glad.PdfViewer
 */
class PdfViewerAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "glad.PdfViewer")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"glad.PdfViewer\">\n"
"    <method name=\"currentDocument\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"syncFromSource\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"sourceFile\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"lineNumber\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    PdfViewerAdaptor(QObject *parent);
    virtual ~PdfViewerAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QString currentDocument();
    void syncFromSource(const QString &sourceFile, int lineNumber);
Q_SIGNALS: // SIGNALS
};

#endif
