/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c PdfViewerInterface -i pdfviewer_interface.h -p :pdfviewer_interface.cpp pdfviewer.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "pdfviewer_interface.h"
/*
 * Implementation of interface class PdfViewerInterface
 */

PdfViewerInterface::PdfViewerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

PdfViewerInterface::~PdfViewerInterface()
{
}

