unix {
	isEmpty(PREFIX): PREFIX = /usr
	isEmpty(INCLUDES_INSTALL_DIR): INCLUDES_INSTALL_DIR = $${PREFIX}/include
	isEmpty(LIB_INSTALL_DIR): LIB_INSTALL_DIR = $${PREFIX}/lib
	isEmpty(DATA_INSTALL_DIR): DATA_INSTALL_DIR = $${PREFIX}/share
	isEmpty(PDFVIEWLIB_DATA_INSTALL_DIR): PDFVIEWLIB_DATA_INSTALL_DIR = $${DATA_INSTALL_DIR}/pdfviewlib
	isEmpty(PDFVIEWLIB_TRANSLATIONS_INSTALL_DIR): PDFVIEWLIB_TRANSLATIONS_INSTALL_DIR = $${PDFVIEWLIB_DATA_INSTALL_DIR}/locale
}
